### ISSUE TITLE
Internal write not working once a new warp connection is made

### ISSUE THREAD

**Issue by arcj0** [warp-contracts/warp#221] opened 2022-09-15 21:21 UTC
To see the issue, here's a test [app](https://github.com/aftrmarket/vue-contract-test)

After the internal write is made, you can see the state change, but if you read the contract using another WarpFactory connection, the claims aren't processed.

**Comment by ppedziwiatr** [comment] 2022-09-16 09:04
Ok, I'm rewriting this to a jest test-case, cause testing and clicking in a browser is really counter productive.

**Comment by ppedziwiatr** [comment] 2022-09-16 11:09
Reproduced in https://github.com/warp-contracts/warp/blob/ppe/aftr-joe-iw-issue/src/__tests__/integration/internal-writes/internal-write-aftr.test.ts#L91

**Comment by ppedziwiatr** [comment] 2022-09-16 11:29
From further analysis - for some reason the interaction with IW does not show on a call stack
<img width="820" alt="image" src="https://user-images.githubusercontent.com/84311757/190629092-5ffea7e8-0d01-406a-aa59-9343209bf5c3.png">

As a result, a tag 'Interact-Write' is not being generated.

**Comment by ppedziwiatr** [comment] 2022-09-16 17:06
ok, I've found the root cause. I'll describe it in more details on Monday, but the fixes and some explanation are in this PR
https://github.com/warp-contracts/warp/pull/223

Most important stuff: 
https://github.com/warp-contracts/warp/pull/223#pullrequestreview-1110971331 (see the comments in the contract code)
https://github.com/warp-contracts/warp/pull/223#discussion_r973219409

Also - I've rewritten your vue example to a jest testcase - 
https://github.com/warp-contracts/warp/pull/223#discussion_r973222958

**Comment by ppedziwiatr** [comment] 2022-09-18 11:36
To sum-up:
Do not make `SmartWeave.contracts.write` and `SmartWeave.contracts.readContractState` in a same parent transaction on the same contract.
The latest state of the callee contract (after making an internal write) is in the result returned by the `SmartWeave.contracts.write`.

**Comment by ppedziwiatr** [comment] 2022-09-18 11:39
added protection in https://github.com/warp-contracts/warp/pull/223#issue-1376187865

**Comment by ppedziwiatr** [comment] 2022-09-19 12:36
released in `1.2.7`

**Closed by ppedziwiatr** 2022-09-19 12:36 UTC
Labels: x-files
